/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.6.4/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    implementation("junit:junit:4.13.2")

    // Lucene dependencies
    implementation("org.apache.lucene:lucene-core:8.11.3")
    implementation("org.apache.lucene:lucene-analyzers-common:8.11.3")
    implementation("org.apache.lucene:lucene-queryparser:8.11.3")

    //Jsoup dependency
    implementation("org.jsoup:jsoup:1.17.2")

}

application {
    // Define the main class for the application.
    mainClass.set("a1.lucene.App")
}

tasks.register<JavaExec>("runLuceneIndex") {
    mainClass.set("main.java.a1.lucene.LuceneIndex")
    classpath = sourceSets["main"].runtimeClasspath
}
